# Generated by Django 5.0.7 on 2024-08-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0011_alter_vendorsourcefile_inventory_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorsource',
            name='file_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
